### ISSUE TITLE
Some doubts about this work.

### ISSUE THREAD

**Issue by ZihaoZheng98** [Evfidiw/MoBA#1]
Hi, nice work. I have a question, why don't you compare MoBA to Lora? In abstract, you stated that lora is not adequate for MSD, however, in experiments, there are only lora experiments on BERT or ViT?

Best regards

**Comment by Evfidiw** [comment]
Thanks for your interesting! We have added the comparison in rebuttal, and we also will add a more detailed comparison in the revised version. Thanks again for your advice!

Best regards


| |
evfxie
|
|
***@***.***
|
---- Replied Message ----
| From | Amiya ***@***.***> |
| Date | 7/30/2024 19:02 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Evfidiw/MoBA] Some doubts about this work. (Issue #1) |

Hi, nice work. I have a question, why don't you compare MoBA to Lora? In abstract, you stated that lora is not adequate for MSD, however, in experiments, there are only lora experiments on BERT or ViT?

Best regards

**Comment by Evfidiw** [comment]
Thanks for your interesting! We have added the comparison in rebuttal, and we also will add a more detailed comparison in the revised version.
